import 'package:flutter/material.dart';
const _bg=Color(0xFF06131F),_surface=Color(0xFF102B3D),_teal=Color(0xFF18D6B0),_amber=Color(0xFFFFB547);
class AdminScreen extends StatelessWidget{const AdminScreen({super.key});@override Widget build(BuildContext context)=>Scaffold(backgroundColor:_bg,appBar:AppBar(title:const Text('Admin Console')),body:ListView(padding:const EdgeInsets.all(16),children:[
 const Text('LOCAL ADMIN PREVIEW',style:TextStyle(fontSize:11,fontWeight:FontWeight.w900,color:_teal,letterSpacing:1)),const SizedBox(height:10),Row(children:[Expanded(child:_Metric('USERS','128',Icons.people_outline)),const SizedBox(width:8),Expanded(child:_Metric('CHIP REQUESTS','6',Icons.toll_outlined)),const SizedBox(width:8),Expanded(child:_Metric('GAMES','342',Icons.sports_esports_outlined))]),const SizedBox(height:18),
 const _Title('CHIP MANAGEMENT'),_AdminTile(icon:Icons.add_circle_outline,title:'Pending Chip Requests',subtitle:'Review player requests • 6 pending',accent:_amber),_AdminTile(icon:Icons.account_balance_wallet_outlined,title:'Adjust Player Chips',subtitle:'Add or reduce virtual chips with audit reason',accent:_teal),_AdminTile(icon:Icons.receipt_long_outlined,title:'Chip Ledger',subtitle:'View all admin balance adjustments'),
 const SizedBox(height:12),const _Title('PLAYER MANAGEMENT'),_AdminTile(icon:Icons.manage_accounts_outlined,title:'Players',subtitle:'Search and review player profiles'),_AdminTile(icon:Icons.block_outlined,title:'Suspend / Restore',subtitle:'Control access for individual accounts'),
 const SizedBox(height:12),const _Title('GAME OPERATIONS'),_AdminTile(icon:Icons.sports_cricket,title:'Cricket Controls',subtitle:'Challenge configuration and availability'),_AdminTile(icon:Icons.style,title:'Teen Patti Controls',subtitle:'Table rules and game configuration'),_AdminTile(icon:Icons.notifications_active_outlined,title:'Send Notification',subtitle:'Prepare player announcements'),
 const SizedBox(height:16),const Text('This screen is UI-only. Admin actions will not change real balances until the trusted backend and Supabase service-role API are connected.',textAlign:TextAlign.center,style:TextStyle(fontSize:10,color:Colors.white38))
 ]));}
class _Metric extends StatelessWidget{final String label,value;final IconData icon;const _Metric(this.label,this.value,this.icon);@override Widget build(BuildContext context)=>Container(height:94,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:_surface,borderRadius:BorderRadius.circular(13)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:_teal),const SizedBox(height:5),Text(value,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:_amber)),Text(label,textAlign:TextAlign.center,style:const TextStyle(fontSize:8,color:Colors.white54))]));}
class _Title extends StatelessWidget{final String text;const _Title(this.text);@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Text(text,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900,color:_teal,letterSpacing:1)));}
class _AdminTile extends StatelessWidget{final IconData icon;final String title,subtitle;final Color accent;const _AdminTile({required this.icon,required this.title,required this.subtitle,this.accent=Colors.white70});@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:8),decoration:BoxDecoration(color:_surface,borderRadius:BorderRadius.circular(13)),child:ListTile(leading:Icon(icon,color:accent),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(subtitle,style:const TextStyle(fontSize:10,color:Colors.white54)),trailing:const Icon(Icons.chevron_right)));}
