import 'package:flutter/material.dart';
import 'cricket_screen.dart';
import 'teen_patti_screen.dart';
import 'game_history_screen.dart';
import 'profile_settings_screen.dart';
import 'notifications_screen.dart';
import 'admin_screen.dart';

const _bg=Color(0xFF06131F),_surface=Color(0xFF0B2030),_surface2=Color(0xFF102B3D),_teal=Color(0xFF18D6B0),_amber=Color(0xFFFFB547);
class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{
 int navIndex=0;void open(Widget page)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>page));
 void showAddChips(){showModalBottomSheet(context:context,backgroundColor:_surface2,showDragHandle:true,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(20,8,20,24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Row(children:[Icon(Icons.toll,color:_amber),SizedBox(width:10),Text('ADD CHIPS',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))]),const SizedBox(height:10),const Text('Virtual chips are controlled by PlayArena admin. Players cannot directly change their balance.',style:TextStyle(color:Colors.white70)),const SizedBox(height:16),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_bg,borderRadius:BorderRadius.circular(12)),child:const Row(children:[Text('Current balance'),Spacer(),Text('10,000',style:TextStyle(color:_amber,fontSize:20,fontWeight:FontWeight.w900))])),const SizedBox(height:12),FilledButton.icon(onPressed:(){Navigator.pop(context);ScaffoldMessenger.of(this.context).showSnackBar(const SnackBar(content:Text('Chip request recorded in preview mode.')));},icon:const Icon(Icons.send_outlined),label:const Text('REQUEST CHIPS')),const SizedBox(height:8),const Text('Preview mode • No purchase or cash redemption',textAlign:TextAlign.center,style:TextStyle(fontSize:11,color:Colors.white54))]))));}
 void nav(int i){setState(()=>navIndex=i);if(i==1)return;if(i==2)open(const GameHistoryScreen());if(i==3)showAddChips();if(i==4)open(const ProfileSettingsScreen());Future.delayed(const Duration(milliseconds:150),(){if(mounted)setState(()=>navIndex=0);});}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:_bg,drawer:_GameDrawer(addChips:showAddChips),bottomNavigationBar:NavigationBar(selectedIndex:navIndex,onDestinationSelected:nav,destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.sports_esports_outlined),label:'Games'),NavigationDestination(icon:Icon(Icons.history),label:'History'),NavigationDestination(icon:Icon(Icons.toll_outlined),label:'Add Chips'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]),body:SafeArea(child:CustomScrollView(slivers:[
 SliverToBoxAdapter(child:Builder(builder:(context)=>Padding(padding:const EdgeInsets.fromLTRB(14,10,14,8),child:Row(children:[IconButton(onPressed:()=>Scaffold.of(context).openDrawer(),icon:const Icon(Icons.menu,size:30)),const SizedBox(width:4),const Expanded(child:Text('PLAYARENA',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,letterSpacing:1.2))),IconButton(onPressed:()=>open(const NotificationsScreen()),icon:const Badge(child:Icon(Icons.notifications_none))),InkWell(onTap:showAddChips,borderRadius:BorderRadius.circular(10),child:Padding(padding:const EdgeInsets.all(5),child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:const [Text('VIRTUAL CHIPS',style:TextStyle(fontSize:9,color:Colors.white54)),Text('10,000',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:_amber)),Text('+ ADD CHIPS',style:TextStyle(fontSize:10,color:_teal,fontWeight:FontWeight.w800))])))])))),
 SliverPadding(padding:const EdgeInsets.symmetric(horizontal:14),sliver:SliverList(delegate:SliverChildListDelegate([
 Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF073A3C),_surface]),borderRadius:BorderRadius.circular(14),border:Border.all(color:_teal.withValues(alpha:.35))),child:const Row(children:[Icon(Icons.campaign_outlined,color:_teal),SizedBox(width:10),Expanded(child:Text('Welcome to PlayArena • Free-play sports & card games',style:TextStyle(fontWeight:FontWeight.w700)))])),const SizedBox(height:14),const Text('QUICK PLAY',style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:Colors.white60,letterSpacing:1.1)),const SizedBox(height:8),
 Row(children:[Expanded(child:_HeroTile(icon:Icons.sports_cricket,title:'Cricket',subtitle:'2-over challenge',accent:_teal,onTap:()=>open(const CricketScreen()))),const SizedBox(width:10),Expanded(child:_HeroTile(icon:Icons.style,title:'Teen Patti',subtitle:'3-card table',accent:_amber,onTap:()=>open(const TeenPattiScreen())))]),const SizedBox(height:18),const Center(child:Text('Current Activities',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700))),const SizedBox(height:10),
 Row(children:[Expanded(child:_ModeTile(icon:Icons.flash_on,title:'Quick\nPlay',active:true)),const SizedBox(width:8),Expanded(child:_ModeTile(icon:Icons.history,title:'Game\nHistory',onTap:()=>open(const GameHistoryScreen()))),const SizedBox(width:8),Expanded(child:_ModeTile(icon:Icons.notifications_outlined,title:'Alerts',onTap:()=>open(const NotificationsScreen()))),const SizedBox(width:8),Expanded(child:_ModeTile(icon:Icons.toll_outlined,title:'Add\nChips',onTap:showAddChips))]),const SizedBox(height:18),
 const _SectionHeader(title:'CRICKET ARENA',icon:Icons.sports_cricket),const SizedBox(height:8),_ActivityCard(live:true,title:'2-Over Batting Challenge',subtitle:'12 balls • 3 wickets',icon:Icons.sports_cricket,button:'PLAY',onTap:()=>open(const CricketScreen())),_ActivityCard(live:false,title:'Power Hitting Challenge',subtitle:'High-risk boundary mode • Coming soon',icon:Icons.bolt,button:'SOON'),const SizedBox(height:12),const _SectionHeader(title:'CARD ARENA',icon:Icons.style),const SizedBox(height:8),_ActivityCard(live:true,title:'Teen Patti Table',subtitle:'Offline table • Bot opponents',icon:Icons.style,button:'PLAY',onTap:()=>open(const TeenPattiScreen())),_ActivityCard(live:false,title:'Multiplayer Tables',subtitle:'Realtime rooms • Planned after backend setup',icon:Icons.groups_outlined,button:'SOON'),const SizedBox(height:12),
 InkWell(onTap:showAddChips,borderRadius:BorderRadius.circular(16),child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF073A3C),_surface2]),borderRadius:BorderRadius.circular(16),border:Border.all(color:_teal.withValues(alpha:.25))),child:const Row(children:[Icon(Icons.toll,size:42,color:_amber),SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('NEED MORE CHIPS?',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Send a chip request. Balance changes remain admin-controlled.',style:TextStyle(color:Colors.white70))])),Icon(Icons.chevron_right,color:_teal)]))),const SizedBox(height:20)
 ]))) ])));
}
class _HeroTile extends StatelessWidget{final IconData icon;final String title,subtitle;final Color accent;final VoidCallback onTap;const _HeroTile({required this.icon,required this.title,required this.subtitle,required this.accent,required this.onTap});@override Widget build(BuildContext context)=>Material(color:_surface,borderRadius:BorderRadius.circular(16),child:InkWell(borderRadius:BorderRadius.circular(16),onTap:onTap,child:Container(height:116,padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:accent.withValues(alpha:.45)),borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:accent,size:30),const Spacer(),Text(title,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),Text(subtitle,style:const TextStyle(fontSize:11,color:Colors.white60))]))));}
class _ModeTile extends StatelessWidget{final IconData icon;final String title;final bool active;final VoidCallback? onTap;const _ModeTile({required this.icon,required this.title,this.active=false,this.onTap});@override Widget build(BuildContext context)=>Material(color:Colors.transparent,child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(12),child:Container(height:82,decoration:BoxDecoration(color:active?const Color(0xFF0B4B48):_surface,borderRadius:BorderRadius.circular(12),border:Border.all(color:active?_teal:Colors.white12)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:active?_teal:Colors.white70),const SizedBox(height:6),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700))]))));}
class _SectionHeader extends StatelessWidget{final String title;final IconData icon;const _SectionHeader({required this.title,required this.icon});@override Widget build(BuildContext context)=>Row(children:[Icon(icon,color:_teal),const SizedBox(width:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w900,letterSpacing:.8)),const Spacer(),const Icon(Icons.chevron_right,color:Colors.white38)]);}
class _ActivityCard extends StatelessWidget{final bool live;final String title,subtitle,button;final IconData icon;final VoidCallback? onTap;const _ActivityCard({required this.live,required this.title,required this.subtitle,required this.icon,required this.button,this.onTap});@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_surface2,borderRadius:BorderRadius.circular(13),border:Border.all(color:Colors.white10)),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:_bg,borderRadius:BorderRadius.circular(12)),child:Icon(icon,color:live?_teal:Colors.white38)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[if(live)...[Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:3),decoration:BoxDecoration(color:_teal.withValues(alpha:.16),borderRadius:BorderRadius.circular(6)),child:const Text('LIVE',style:TextStyle(color:_teal,fontSize:9,fontWeight:FontWeight.w900))),const SizedBox(width:7)],Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)))]),const SizedBox(height:4),Text(subtitle,style:const TextStyle(fontSize:11,color:Colors.white60))])),const SizedBox(width:8),FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:live?_teal:Colors.white12,foregroundColor:live?_bg:Colors.white54,padding:const EdgeInsets.symmetric(horizontal:13)),child:Text(button))]));}
class _GameDrawer extends StatelessWidget{final VoidCallback addChips;const _GameDrawer({required this.addChips});void go(BuildContext c,Widget p){Navigator.pop(c);Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}@override Widget build(BuildContext context)=>Drawer(backgroundColor:const Color(0xFF07121B),child:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const TextField(decoration:InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search PlayArena',filled:true,border:OutlineInputBorder(borderSide:BorderSide.none))),const SizedBox(height:22),const Text('GAMES',style:TextStyle(fontWeight:FontWeight.w900,color:Colors.white54)),ListTile(leading:const Icon(Icons.sports_cricket,color:_teal),title:const Text('Cricket'),onTap:()=>go(context,const CricketScreen())),ListTile(leading:const Icon(Icons.style,color:_amber),title:const Text('Teen Patti'),onTap:()=>go(context,const TeenPattiScreen())),const Divider(),const Text('ACCOUNT',style:TextStyle(fontWeight:FontWeight.w900,color:Colors.white54)),ListTile(leading:const Icon(Icons.toll_outlined,color:_amber),title:const Text('Add Chips'),onTap:(){Navigator.pop(context);addChips();}),ListTile(leading:const Icon(Icons.history),title:const Text('Game History'),onTap:()=>go(context,const GameHistoryScreen())),ListTile(leading:const Icon(Icons.notifications_outlined),title:const Text('Notifications'),onTap:()=>go(context,const NotificationsScreen())),ListTile(leading:const Icon(Icons.person_outline),title:const Text('Profile & Settings'),onTap:()=>go(context,const ProfileSettingsScreen())),const Divider(),const Text('DEVELOPMENT',style:TextStyle(fontWeight:FontWeight.w900,color:Colors.white54)),ListTile(leading:const Icon(Icons.admin_panel_settings_outlined,color:_teal),title:const Text('Admin Console'),subtitle:const Text('Local UI preview'),onTap:()=>go(context,const AdminScreen())),const ListTile(leading:Icon(Icons.groups_outlined),title:Text('Multiplayer Rooms'),subtitle:Text('Coming later')),const ListTile(leading:Icon(Icons.emoji_events_outlined),title:Text('Challenges & Leaderboards'),subtitle:Text('Coming later'))])));}
